### ISSUE TITLE
Tvorba katalógu požiadaviek

### ISSUE THREAD

**Issue by bublavy3** [TIS2023-FMFI/sportovy-pretek#2]
Jadro dokumentu je hotové, ostávajú vizuálne úpravy a pridanie referencii.

**Comment by pavelpetrovic** [comment]
na teams mi prosim poslite notifikaciu s linkou na najnovsiu verziu po upravach na zaklade diskusie so zadavatelom o tom, co vsetko mozu statistiky zobrazovat a doladeni formulacie poziadaviek

[katalog_poziadaviek_sport_s_postrehmi.docx](https://github.com/TIS2023-FMFI/sportovy-pretek/files/13053611/katalog_poziadaviek_sport_s_postrehmi.docx)

**Comment by pavelpetrovic** [comment]
Produkt dokáže pridať do databázy klubovej aplikácie novú vekovú kategóriu a jej atribút, ktorým je názov (reťazec).

  => ma byt jasne, ze doteraz to slo cez GUI a uz to pojde aj z command line  (plati globalne - mozete to vybavit aj nejakou vseobecnou delkaraciou na zaciatku, ale tak aby to bolo celkom jednoznacne coho sa to tyka)
  
Produkt dokáže pridať do databázy klubovej aplikácie nové preteky a ich atribúty, ktorými sú názov (reťazec), dátum a čas konania a deadline prihlasovania.

  => chyba mi info, ze ide o vybrate preteky z SK servra
  
Používateľ si môže zobraziť zoznam všetkých budúcich pretekov
  
  => dtto
  
Používateľ môže zúžiť zoznam pretekov výberom mesiaca, v ktorom sa majú konať.

  => zoznam prektekov z SK servra
  
2. Pridanie pretekov

   => chyba mi info, ci pridane preteky budu aktivne a ci bude command line umoznovat nastavit ci su aktivne
   
identifikovali sme redundancie, prosim, vycistit a zapisat zrozumitelne, jasne
systematicky, kazda poziadavka sama o sebe je citatelna aj v inom poradi, obsahuje vsetky potrebne
informacie o funkcionalite pre pouzivatela
