### ISSUE TITLE
Návrh používateľského rozhrania

### ISSUE THREAD

**Issue by DavidK276** [TIS2023-FMFI/sportovy-pretek#6]
Aplikácia sa bude ovládať pomocou CLI, treba ho navrhnút.

**Comment by DavidK276** [comment]
Na stretnutí sme vypracovali prvý návrh rozhrania.
[sportovy-pretek-cli.md](https://github.com/TIS2023-FMFI/sportovy-pretek/files/13113741/sportovy-pretek-cli.md)

**Comment by DavidK276** [comment]
Pridal som mockup prihlasovania používateľov.

**Comment by czere7** [comment]
Spravil som mokup pre pridanie novych pretekov
